### ISSUE TITLE
UWP Track() COMException 

### ISSUE THREAD

**Issue by fileman** [colbylwilliams/VersionTrackingPlugin#8]
Hi, what's the right place of CrossVersionTracking.Current.Track() in UWP Xamarin.Forms ?
I' always get this:
```
System.Runtime.InteropServices.COMException occurred
  HResult=0x8007065E
  Message=Data of this type is not supported.

Error trying to serialize the value to be written to the application data store
  Source=
  StackTrace:
   at System.Runtime.InteropServices.WindowsRuntime.IMap`2.Insert(K key, V value)
   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Insert[K,V](IMap`2 _this, K key, V value)
   at System.Runtime.InteropServices.WindowsRuntime.MapToDictionaryAdapter.Indexer_Set[K,V](K key, V value)
   at Plugin.VersionTracking.VersionTrackingImplementation.Track()
   at Xamarin.UWP.MainPage..ctor() in C:\...\Xamarin.UWP\MainPage.xaml.cs:line 24
   at Xamarin.UWP.Xamarin_UWP_XamlTypeInfo.XamlTypeInfoProvider.Activate_4_MainPage() in C:\...\Xamarin.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 207
   at Xamarin.UWP.Xamarin_UWP_XamlTypeInfo.XamlUserType.ActivateInstance() in C:\...\Xamarin.UWP\obj\x86\Debug\XamlTypeInfo.g.cs:line 435
```

**Comment by fileman** [comment]
Solved with Json PR  #9
